"""membri degli stack

Revision ID: 3e16596911e0
Revises: 2d4456551dfd
Create Date: 2026-10-07 20:43:16.150454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e16596911e0'
down_revision: Union[str, None] = '2d4456551dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stack_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('rack_position', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_stack_members_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stack_members')),
    sa.UniqueConstraint('device_id', 'number', name=op.f('uq_stack_members_device_id_number'))
    )
    op.create_index(op.f('ix_stack_members_device_id'), 'stack_members', ['device_id'], unique=False)
    op.create_index(op.f('ix_stack_members_serial'), 'stack_members', ['serial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stack_members_serial'), table_name='stack_members')
    op.drop_index(op.f('ix_stack_members_device_id'), table_name='stack_members')
    op.drop_table('stack_members')
    # ### end Alembic commands ###
