"""sfondo delle mappe

Revision ID: 7bab7a715665
Revises: 4cb75a87edc5
Create Date: 2026-10-10 18:40:15.063641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bab7a715665'
down_revision: Union[str, None] = '4cb75a87edc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_backgrounds',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], name=op.f('fk_map_backgrounds_map_id_maps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', name=op.f('pk_map_backgrounds'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_backgrounds')
    # ### end Alembic commands ###
