"""fase 4 stato live endpoint login

Revision ID: 31e48942e0d8
Revises: e11256680444
Create Date: 2026-10-05 23:38:56.868921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e48942e0d8'
down_revision: Union[str, None] = 'e11256680444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='viewer', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('interface_id', sa.Integer(), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('macs_on_port', sa.Integer(), nullable=True),
    sa.Column('previous_interface_id', sa.Integer(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], name=op.f('fk_endpoints_interface_id_interfaces'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_interface_id'], ['interfaces.id'], name=op.f('fk_endpoints_previous_interface_id_interfaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endpoints')),
    sa.UniqueConstraint('mac', name=op.f('uq_endpoints_mac'))
    )
    op.create_index(op.f('ix_endpoints_interface_id'), 'endpoints', ['interface_id'], unique=False)
    op.create_index(op.f('ix_endpoints_ip'), 'endpoints', ['ip'], unique=False)
    op.add_column('devices', sa.Column('reachable', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('reachable_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('rtt_ms', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('snmp_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_devices_snmp_profile_id_snmp_profiles'), 'devices', 'snmp_profiles', ['snmp_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_devices_snmp_profile_id_snmp_profiles'), 'devices', type_='foreignkey')
    op.drop_column('devices', 'snmp_profile_id')
    op.drop_column('devices', 'rtt_ms')
    op.drop_column('devices', 'reachable_changed_at')
    op.drop_column('devices', 'last_check_at')
    op.drop_column('devices', 'reachable')
    op.drop_index(op.f('ix_endpoints_ip'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_interface_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_table('users')
    # ### end Alembic commands ###
