"""ruolo predefinito del modello

Revision ID: ff01f7d53204
Revises: 8da9f4d344eb
Create Date: 2026-10-07 14:57:07.451243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff01f7d53204'
down_revision: Union[str, None] = '8da9f4d344eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_types', sa.Column('default_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_device_types_default_role_id_device_roles'), 'device_types', 'device_roles', ['default_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_device_types_default_role_id_device_roles'), 'device_types', type_='foreignkey')
    op.drop_column('device_types', 'default_role_id')
    # ### end Alembic commands ###
