"""avvisi per sede, ruolo, device e porte; modelli dei messaggi

Revision ID: c992f256ba05
Revises: b15a4320cf0d
Create Date: 2026-10-10 00:11:29.978555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c992f256ba05'
down_revision: Union[str, None] = 'b15a4320cf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_channels', sa.Column('site_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('alert_channels', sa.Column('location_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('alert_channels', sa.Column('role_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('alert_channels', sa.Column('device_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('alert_channels', sa.Column('ports', sa.String(length=10), server_default='none', nullable=False))
    op.add_column('alert_channels', sa.Column('interface_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('alert_channels', sa.Column('templates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
    op.add_column('alert_states', sa.Column('interface_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_alert_states_channel_id_device_id'), 'alert_states', type_='unique')
    op.create_index(op.f('ix_alert_states_interface_id'), 'alert_states', ['interface_id'], unique=False)
    op.create_unique_constraint(op.f('uq_alert_states_channel_id_device_id_interface_id'), 'alert_states', ['channel_id', 'device_id', 'interface_id'])
    op.create_foreign_key(op.f('fk_alert_states_interface_id_interfaces'), 'alert_states', 'interfaces', ['interface_id'], ['id'], ondelete='CASCADE')
    op.add_column('interfaces', sa.Column('oper_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interfaces', 'oper_changed_at')
    op.drop_constraint(op.f('fk_alert_states_interface_id_interfaces'), 'alert_states', type_='foreignkey')
    op.drop_constraint(op.f('uq_alert_states_channel_id_device_id_interface_id'), 'alert_states', type_='unique')
    op.drop_index(op.f('ix_alert_states_interface_id'), table_name='alert_states')
    op.create_unique_constraint(op.f('uq_alert_states_channel_id_device_id'), 'alert_states', ['channel_id', 'device_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('alert_states', 'interface_id')
    op.drop_column('alert_channels', 'templates')
    op.drop_column('alert_channels', 'interface_ids')
    op.drop_column('alert_channels', 'ports')
    op.drop_column('alert_channels', 'device_ids')
    op.drop_column('alert_channels', 'role_ids')
    op.drop_column('alert_channels', 'location_ids')
    op.drop_column('alert_channels', 'site_ids')
    # ### end Alembic commands ###
