"""lingua dei canali di avviso

Revision ID: 33b674e39013
Revises: 3e16596911e0
Create Date: 2026-10-08 07:28:16.346277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b674e39013'
down_revision: Union[str, None] = '3e16596911e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_channels', sa.Column('language', sa.String(length=2), server_default='it', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_channels', 'language')
    # ### end Alembic commands ###
