"""import da altre sorgenti

Revision ID: 4cb75a87edc5
Revises: 43996c46479c
Create Date: 2026-10-10 00:32:38.817746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb75a87edc5'
down_revision: Union[str, None] = '43996c46479c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_runs', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('import_runs', sa.Column('default_site', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
    # Non solo NetBox: la versione è quella della sorgente (rinominata, così gli import passati la tengono)
    op.alter_column('import_runs', 'netbox_version', new_column_name='source_version')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_runs', 'source_version', new_column_name='netbox_version')
    op.drop_column('import_runs', 'default_site')
    op.drop_column('import_runs', 'username')
    # ### end Alembic commands ###
