"""accesso con active directory

Revision ID: 316b940deae9
Revises: 69edf6bae0ef
Create Date: 2026-10-09 07:20:31.203440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316b940deae9'
down_revision: Union[str, None] = '69edf6bae0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('servers', sa.String(length=500), server_default='', nullable=False),
    sa.Column('security', sa.String(length=10), server_default='ldaps', nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('verify_cert', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ca_cert', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), server_default='', nullable=False),
    sa.Column('base_dn', sa.String(length=500), nullable=True),
    sa.Column('admin_group', sa.String(length=500), nullable=True),
    sa.Column('editor_group', sa.String(length=500), nullable=True),
    sa.Column('viewer_group', sa.String(length=500), nullable=True),
    sa.Column('default_role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directory_settings'))
    )
    op.add_column('users', sa.Column('source', sa.String(length=20), server_default='local', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'source')
    op.drop_table('directory_settings')
    # ### end Alembic commands ###
