"""avvisi

Revision ID: 241f41b3fd80
Revises: ff01f7d53204
Create Date: 2026-10-07 15:04:45.645030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '241f41b3fd80'
down_revision: Union[str, None] = 'ff01f7d53204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), server_default='5', nullable=False),
    sa.Column('notify_recovery', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_to', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_security', sa.String(length=10), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('webhook_format', sa.String(length=10), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('secret_enc', sa.Text(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_channels')),
    sa.UniqueConstraint('name', name=op.f('uq_alert_channels_name'))
    )
    op.create_table('alert_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('down_since', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['alert_channels.id'], name=op.f('fk_alert_states_channel_id_alert_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_alert_states_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_states')),
    sa.UniqueConstraint('channel_id', 'device_id', name=op.f('uq_alert_states_channel_id_device_id'))
    )
    op.create_index(op.f('ix_alert_states_channel_id'), 'alert_states', ['channel_id'], unique=False)
    op.create_index(op.f('ix_alert_states_device_id'), 'alert_states', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_states_device_id'), table_name='alert_states')
    op.drop_index(op.f('ix_alert_states_channel_id'), table_name='alert_states')
    op.drop_table('alert_states')
    op.drop_table('alert_channels')
    # ### end Alembic commands ###
