"""storico modifiche

Revision ID: 8da9f4d344eb
Revises: 31e48942e0d8
Create Date: 2026-10-07 14:52:49.671523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8da9f4d344eb'
down_revision: Union[str, None] = '31e48942e0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_id_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_device_id'), 'audit_log', ['device_id'], unique=False)
    op.create_index(op.f('ix_audit_log_device_id_2'), 'audit_log', ['device_id_2'], unique=False)
    op.create_index(op.f('ix_audit_log_object_id'), 'audit_log', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_log_object_type'), 'audit_log', ['object_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_object_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_object_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_device_id_2'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_device_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
