"""estremita dei cavi in mappa

Revision ID: 2d4456551dfd
Revises: ea906dbde2e3
Create Date: 2026-10-07 17:21:29.556030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4456551dfd'
down_revision: Union[str, None] = 'ea906dbde2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_cable_routes', sa.Column('ends', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_cable_routes', 'ends')
    # ### end Alembic commands ###
