"""piano delle posizioni

Revision ID: 8b3b3077ecda
Revises: 78baefd0a3bb
Create Date: 2026-10-08 13:24:02.325577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3b3077ecda'
down_revision: Union[str, None] = '78baefd0a3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('floor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'floor')
    # ### end Alembic commands ###
