"""percorso delle posizioni

Revision ID: 78baefd0a3bb
Revises: 33b674e39013
Create Date: 2026-10-08 12:03:30.831702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78baefd0a3bb'
down_revision: Union[str, None] = '33b674e39013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('path', sa.String(length=1000).with_variant(sa.String(length=1000, collation='C'), 'postgresql'), server_default='', nullable=False))
    # ### end Alembic commands ###
    # Percorso delle posizioni esistenti, dal livello più alto in giù
    op.execute("""
        WITH RECURSIVE tree(id, path) AS (
            SELECT id, name::text FROM locations WHERE parent_id IS NULL
            UNION ALL
            SELECT l.id, tree.path || ' › ' || l.name FROM locations l JOIN tree ON l.parent_id = tree.id
        )
        UPDATE locations SET path = tree.path FROM tree WHERE locations.id = tree.id
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'path')
    # ### end Alembic commands ###
