"""copie dei backup fuori dal server

Revision ID: 69edf6bae0ef
Revises: 6de2c9aae91c
Create Date: 2026-10-09 01:03:29.080224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69edf6bae0ef'
down_revision: Union[str, None] = '6de2c9aae91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('share', sa.String(length=255), nullable=True),
    sa.Column('folder', sa.String(length=500), server_default='', nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=True),
    sa.Column('private_key_enc', sa.Text(), nullable=True),
    sa.Column('host_key', sa.Text(), nullable=True),
    sa.Column('keep_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('include_key', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_copy_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_targets')),
    sa.UniqueConstraint('name', name=op.f('uq_backup_targets_name'))
    )
    op.create_table('backup_copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('copied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['backup_targets.id'], name=op.f('fk_backup_copies_target_id_backup_targets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_copies')),
    sa.UniqueConstraint('target_id', 'file', name=op.f('uq_backup_copies_target_id_file'))
    )
    op.create_index(op.f('ix_backup_copies_target_id'), 'backup_copies', ['target_id'], unique=False)
    op.create_table('backup_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='queued', nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['backup_targets.id'], name=op.f('fk_backup_tasks_target_id_backup_targets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_tasks'))
    )
    op.create_index(op.f('ix_backup_tasks_target_id'), 'backup_tasks', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_tasks_target_id'), table_name='backup_tasks')
    op.drop_table('backup_tasks')
    op.drop_index(op.f('ix_backup_copies_target_id'), table_name='backup_copies')
    op.drop_table('backup_copies')
    op.drop_table('backup_targets')
    # ### end Alembic commands ###
