"""nome e cognome degli utenti

Revision ID: b15a4320cf0d
Revises: 9f1567eded42
Create Date: 2026-10-09 23:53:50.960588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15a4320cf0d'
down_revision: Union[str, None] = '9f1567eded42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
    # "Nome e cognome" di prima: la prima parola è il nome, il resto il cognome (si corregge dalla pagina Utenti;
    # gli utenti di dominio li riprendono da givenName e sn al prossimo accesso)
    op.execute("""
        UPDATE users SET
            first_name = NULLIF(split_part(btrim(full_name), ' ', 1), ''),
            last_name = NULLIF(btrim(substr(btrim(full_name), length(split_part(btrim(full_name), ' ', 1)) + 1)), '')
        WHERE full_name IS NOT NULL
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
