"""iniziale

Revision ID: 977883bc421e
Revises: 
Create Date: 2026-10-05 17:15:34.699769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '977883bc421e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), server_default='#888780', nullable=False),
    sa.Column('level', sa.Integer(), server_default='2', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_device_roles_name'))
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('name', name=op.f('uq_manufacturers_name'))
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('name', name=op.f('uq_sites_name'))
    )
    op.create_table('vrfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rd', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vrfs')),
    sa.UniqueConstraint('name', name=op.f('uq_vrfs_name')),
    sa.UniqueConstraint('rd', name=op.f('uq_vrfs_rd'))
    )
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('u_height', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sys_object_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_device_types_manufacturer_id_manufacturers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_types')),
    sa.UniqueConstraint('manufacturer_id', 'model', name=op.f('uq_device_types_manufacturer_id_model')),
    sa.UniqueConstraint('sys_object_id', name=op.f('uq_device_types_sys_object_id'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], name=op.f('fk_locations_parent_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_locations_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('site_id', 'parent_id', 'name', name=op.f('uq_locations_site_id_parent_id_name'))
    )
    op.create_index(op.f('ix_locations_site_id'), 'locations', ['site_id'], unique=False)
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('vid BETWEEN 1 AND 4094', name=op.f('ck_vlans_vid_range')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_vlans_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vlans')),
    sa.UniqueConstraint('site_id', 'vid', name=op.f('uq_vlans_site_id_vid'))
    )
    op.create_index(op.f('ix_vlans_site_id'), 'vlans', ['site_id'], unique=False)
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('auto_include', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_maps_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_maps_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maps')),
    sa.UniqueConstraint('name', name=op.f('uq_maps_name'))
    )
    op.create_index(op.f('ix_maps_site_id'), 'maps', ['site_id'], unique=False)
    op.create_table('prefixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('sort_key', sa.LargeBinary(length=18), nullable=False),
    sa.Column('vrf_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_prefixes_site_id_sites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], name=op.f('fk_prefixes_vlan_id_vlans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vrf_id'], ['vrfs.id'], name=op.f('fk_prefixes_vrf_id_vrfs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prefixes')),
    sa.UniqueConstraint('vrf_id', 'prefix', name=op.f('uq_prefixes_vrf_id_prefix'))
    )
    op.create_index(op.f('ix_prefixes_sort_key'), 'prefixes', ['sort_key'], unique=False)
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('u_height', sa.Integer(), server_default='42', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_racks_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_racks_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_racks')),
    sa.UniqueConstraint('site_id', 'name', name=op.f('uq_racks_site_id_name'))
    )
    op.create_index(op.f('ix_racks_site_id'), 'racks', ['site_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('rack_position', sa.Integer(), nullable=True),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('sys_name', sa.String(length=255), nullable=True),
    sa.Column('sys_descr', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_types.id'], name=op.f('fk_devices_device_type_id_device_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_devices_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], name=op.f('fk_devices_rack_id_racks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['device_roles.id'], name=op.f('fk_devices_role_id_device_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_devices_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('asset_tag', name=op.f('uq_devices_asset_tag')),
    sa.UniqueConstraint('site_id', 'name', name=op.f('uq_devices_site_id_name'))
    )
    op.create_index(op.f('ix_devices_serial'), 'devices', ['serial'], unique=False)
    op.create_index(op.f('ix_devices_site_id'), 'devices', ['site_id'], unique=False)
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), server_default='copper', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('mgmt_only', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('untagged_vlan_id', sa.Integer(), nullable=True),
    sa.Column('lag_id', sa.Integer(), nullable=True),
    sa.Column('if_index', sa.Integer(), nullable=True),
    sa.Column('oper_status', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_interfaces_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lag_id'], ['interfaces.id'], name=op.f('fk_interfaces_lag_id_interfaces'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['untagged_vlan_id'], ['vlans.id'], name=op.f('fk_interfaces_untagged_vlan_id_vlans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interfaces')),
    sa.UniqueConstraint('device_id', 'name', name=op.f('uq_interfaces_device_id_name'))
    )
    op.create_index(op.f('ix_interfaces_device_id'), 'interfaces', ['device_id'], unique=False)
    op.create_index(op.f('ix_interfaces_mac_address'), 'interfaces', ['mac_address'], unique=False)
    op.create_table('map_nodes',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_map_nodes_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], name=op.f('fk_map_nodes_map_id_maps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', 'device_id', name=op.f('pk_map_nodes'))
    )
    op.create_table('cables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_interface_id', sa.Integer(), nullable=False),
    sa.Column('b_interface_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='connected', nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('length_unit', sa.String(length=5), server_default='m', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('a_interface_id <> b_interface_id', name=op.f('ck_cables_distinct_ends')),
    sa.ForeignKeyConstraint(['a_interface_id'], ['interfaces.id'], name=op.f('fk_cables_a_interface_id_interfaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['b_interface_id'], ['interfaces.id'], name=op.f('fk_cables_b_interface_id_interfaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cables')),
    sa.UniqueConstraint('a_interface_id', name=op.f('uq_cables_a_interface_id')),
    sa.UniqueConstraint('b_interface_id', name=op.f('uq_cables_b_interface_id'))
    )
    op.create_table('interface_tagged_vlans',
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], name=op.f('fk_interface_tagged_vlans_interface_id_interfaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], name=op.f('fk_interface_tagged_vlans_vlan_id_vlans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interface_id', 'vlan_id', name=op.f('pk_interface_tagged_vlans'))
    )
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=45), nullable=False),
    sa.Column('sort_key', sa.LargeBinary(length=17), nullable=False),
    sa.Column('vrf_id', sa.Integer(), nullable=True),
    sa.Column('interface_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('dns_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], name=op.f('fk_ip_addresses_interface_id_interfaces'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vrf_id'], ['vrfs.id'], name=op.f('fk_ip_addresses_vrf_id_vrfs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ip_addresses')),
    sa.UniqueConstraint('vrf_id', 'host', name=op.f('uq_ip_addresses_vrf_id_host'))
    )
    op.create_index(op.f('ix_ip_addresses_host'), 'ip_addresses', ['host'], unique=False)
    op.create_index(op.f('ix_ip_addresses_interface_id'), 'ip_addresses', ['interface_id'], unique=False)
    op.create_index(op.f('ix_ip_addresses_sort_key'), 'ip_addresses', ['sort_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_addresses_sort_key'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_interface_id'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_host'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_table('interface_tagged_vlans')
    op.drop_table('cables')
    op.drop_table('map_nodes')
    op.drop_index(op.f('ix_interfaces_mac_address'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_device_id'), table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_index(op.f('ix_devices_site_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_serial'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_racks_site_id'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_prefixes_sort_key'), table_name='prefixes')
    op.drop_table('prefixes')
    op.drop_index(op.f('ix_maps_site_id'), table_name='maps')
    op.drop_table('maps')
    op.drop_index(op.f('ix_vlans_site_id'), table_name='vlans')
    op.drop_table('vlans')
    op.drop_index(op.f('ix_locations_site_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('device_types')
    op.drop_table('vrfs')
    op.drop_table('sites')
    op.drop_table('manufacturers')
    op.drop_table('device_roles')
    # ### end Alembic commands ###
