"""scansione snmp

Revision ID: e11256680444
Revises: 1a6c6b905200
Create Date: 2026-10-05 20:32:03.121733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e11256680444'
down_revision: Union[str, None] = '1a6c6b905200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snmp_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=5), server_default='v2c', nullable=False),
    sa.Column('port', sa.Integer(), server_default='161', nullable=False),
    sa.Column('timeout', sa.Float(), server_default='2', nullable=False),
    sa.Column('retries', sa.Integer(), server_default='1', nullable=False),
    sa.Column('community_enc', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('auth_protocol', sa.String(length=10), nullable=True),
    sa.Column('auth_key_enc', sa.Text(), nullable=True),
    sa.Column('priv_protocol', sa.String(length=10), nullable=True),
    sa.Column('priv_key_enc', sa.Text(), nullable=True),
    sa.Column('context_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snmp_profiles')),
    sa.UniqueConstraint('name', name=op.f('uq_snmp_profiles_name'))
    )
    op.create_table('discovery_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('profile_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('auto_new_interfaces', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('auto_new_ips', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_discovery_jobs_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_jobs')),
    sa.UniqueConstraint('name', name=op.f('uq_discovery_jobs_name'))
    )
    op.create_index(op.f('ix_discovery_jobs_site_id'), 'discovery_jobs', ['site_id'], unique=False)
    op.create_table('discovery_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hosts_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hosts_responded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('changes_proposed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('changes_applied', sa.Integer(), server_default='0', nullable=False),
    sa.Column('log', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['discovery_jobs.id'], name=op.f('fk_discovery_runs_job_id_discovery_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_runs'))
    )
    op.create_index(op.f('ix_discovery_runs_job_id'), 'discovery_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_discovery_runs_status'), 'discovery_runs', ['status'], unique=False)
    op.create_table('discovery_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=45), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_label', sa.String(length=255), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('auto', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_discovery_changes_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['discovery_jobs.id'], name=op.f('fk_discovery_changes_job_id_discovery_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['discovery_runs.id'], name=op.f('fk_discovery_changes_run_id_discovery_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_changes'))
    )
    op.create_index(op.f('ix_discovery_changes_device_id'), 'discovery_changes', ['device_id'], unique=False)
    op.create_index(op.f('ix_discovery_changes_job_id'), 'discovery_changes', ['job_id'], unique=False)
    op.create_index(op.f('ix_discovery_changes_key'), 'discovery_changes', ['key'], unique=False)
    op.create_index(op.f('ix_discovery_changes_run_id'), 'discovery_changes', ['run_id'], unique=False)
    op.create_index(op.f('ix_discovery_changes_status'), 'discovery_changes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovery_changes_status'), table_name='discovery_changes')
    op.drop_index(op.f('ix_discovery_changes_run_id'), table_name='discovery_changes')
    op.drop_index(op.f('ix_discovery_changes_key'), table_name='discovery_changes')
    op.drop_index(op.f('ix_discovery_changes_job_id'), table_name='discovery_changes')
    op.drop_index(op.f('ix_discovery_changes_device_id'), table_name='discovery_changes')
    op.drop_table('discovery_changes')
    op.drop_index(op.f('ix_discovery_runs_status'), table_name='discovery_runs')
    op.drop_index(op.f('ix_discovery_runs_job_id'), table_name='discovery_runs')
    op.drop_table('discovery_runs')
    op.drop_index(op.f('ix_discovery_jobs_site_id'), table_name='discovery_jobs')
    op.drop_table('discovery_jobs')
    op.drop_table('snmp_profiles')
    # ### end Alembic commands ###
