"""punti di ancoraggio dei cavi

Revision ID: ea906dbde2e3
Revises: 241f41b3fd80
Create Date: 2026-10-07 16:06:55.041920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea906dbde2e3'
down_revision: Union[str, None] = '241f41b3fd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_cable_routes',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('cable_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], name=op.f('fk_map_cable_routes_cable_id_cables'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], name=op.f('fk_map_cable_routes_map_id_maps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', 'cable_id', name=op.f('pk_map_cable_routes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_cable_routes')
    # ### end Alembic commands ###
